spring:
  application:
    name: POLICY-SERVICE

server:
  port: 9094

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

      
      

       